# Generated by Django 4.1.9 on 2023-07-04 09:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utilities.json


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("extras", "0092_delete_jobresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("custom_field_data", models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ("started", models.DateTimeField(blank=True, null=True)),
                ("completed", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=30)),
                ("scheduled", models.DateTimeField(blank=True, null=True)),
                ("interval", models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ("task_id", models.UUIDField(unique=True)),
                ("data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-started",),
            },
        ),
        migrations.CreateModel(
            name="ScriptInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("module_path", models.CharField(max_length=1000)),
                ("class_name", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="ScriptLogLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("custom_field_data", models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ("level", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "script_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="script_log_lines",
                        to="netbox_script_manager.scriptexecution",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ("timestamp",),
            },
        ),
        migrations.AddIndex(
            model_name="scriptinstance",
            index=models.Index(fields=["name"], name="netbox_plug_name_564a70_idx"),
        ),
        migrations.AddField(
            model_name="scriptexecution",
            name="script_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="script_executions", to="netbox_script_manager.scriptinstance"
            ),
        ),
        migrations.AddField(
            model_name="scriptexecution",
            name="tags",
            field=taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AddIndex(
            model_name="scriptlogline",
            index=models.Index(fields=["level"], name="netbox_plug_level_8d819d_idx"),
        ),
        migrations.AddIndex(
            model_name="scriptlogline",
            index=models.Index(fields=["timestamp"], name="netbox_plug_timesta_0d3feb_idx"),
        ),
        migrations.AddIndex(
            model_name="scriptexecution",
            index=models.Index(fields=["started"], name="netbox_plug_started_b32370_idx"),
        ),
        migrations.AddIndex(
            model_name="scriptexecution",
            index=models.Index(fields=["completed"], name="netbox_plug_complet_95a239_idx"),
        ),
    ]
