# Generated by Django 4.2.4 on 2023-09-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_script_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptexecution",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
