# Generated by Django 4.1.9 on 2023-07-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_script_manager", "0002_scriptinstance_custom_field_data_scriptinstance_tags"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="scriptinstance",
            constraint=models.UniqueConstraint(
                fields=("module_path", "class_name"), name="netbox_script_manager_scriptinstance_unique_module_path_class_name"
            ),
        ),
    ]
