# Generated by Django 4.2.4 on 2023-10-09 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0011_contactassignment_tags"),
        ("netbox_script_manager", "0002_scriptexecution_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptinstance",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="tenancy.tenant"
            ),
        ),
    ]
