# Generated by Django 4.1.9 on 2023-07-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_script_manager", "0003_scriptinstance_netbox_plugin_script_manager_scriptinstance_unique_module_path_class_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptinstance",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
