# Generated by Django 4.2.2 on 2023-07-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_script_manager", "0004_scriptinstance_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scriptexecution",
            name="created",
        ),
        migrations.RemoveField(
            model_name="scriptexecution",
            name="custom_field_data",
        ),
        migrations.RemoveField(
            model_name="scriptexecution",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="scriptexecution",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="scriptlogline",
            name="created",
        ),
        migrations.RemoveField(
            model_name="scriptlogline",
            name="custom_field_data",
        ),
        migrations.RemoveField(
            model_name="scriptlogline",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="scriptlogline",
            name="tags",
        ),
        migrations.CreateModel(
            name="ScriptArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("data", models.BinaryField()),
                ("content_type", models.CharField(max_length=100)),
                (
                    "script_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="script_artifacts",
                        to="netbox_script_manager.scriptexecution",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
