# Generated by Django 4.2.2 on 2023-07-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_script_manager", "0005_remove_scriptexecution_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptartifact",
            name="name",
            field=models.CharField(default="text/plain", max_length=100),
        ),
    ]
