# Generated by Django 4.2.2 on 2023-07-28 05:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_script_manager", "0007_scriptexecution_created_scriptexecution_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scriptexecution",
            options={"ordering": ("-created",)},
        ),
    ]
