# Generated by Django 4.1.10 on 2023-08-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_script_manager", "0008_alter_scriptexecution_options"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="scriptexecution",
            new_name="netbox_scri_started_ca0f36_idx",
            old_name="netbox_plug_started_b32370_idx",
        ),
        migrations.RenameIndex(
            model_name="scriptexecution",
            new_name="netbox_scri_complet_0824df_idx",
            old_name="netbox_plug_complet_95a239_idx",
        ),
        migrations.RenameIndex(
            model_name="scriptinstance",
            new_name="netbox_scri_name_d36576_idx",
            old_name="netbox_plug_name_564a70_idx",
        ),
        migrations.RenameIndex(
            model_name="scriptlogline",
            new_name="netbox_scri_level_8445b8_idx",
            old_name="netbox_plug_level_8d819d_idx",
        ),
        migrations.RenameIndex(
            model_name="scriptlogline",
            new_name="netbox_scri_timesta_535a98_idx",
            old_name="netbox_plug_timesta_0d3feb_idx",
        ),
        migrations.AddField(
            model_name="scriptinstance",
            name="task_queue",
            field=models.CharField(default="default", max_length=100),
        ),
    ]
