# Generated by Django 4.1.10 on 2023-08-21 11:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "netbox_script_manager",
            "0009_rename_netbox_plug_started_b32370_idx_netbox_scri_started_ca0f36_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scriptinstance",
            name="task_queue",
        ),
        migrations.AddField(
            model_name="scriptinstance",
            name="task_queues",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
