# Generated by Django 4.1.10 on 2023-08-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_script_manager", "0010_remove_scriptinstance_task_queue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptinstance",
            name="group",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
