# Generated by Django 4.1.10 on 2023-08-28 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_script_manager", "0012_scriptinstance_weight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scriptinstance",
            options={"ordering": ("group", "-weight", "name")},
        ),
    ]
