# Generated by Django 4.1.10 on 2023-08-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_script_manager", "0013_alter_scriptinstance_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptexecution",
            name="task_queue",
            field=models.CharField(default="default", max_length=100),
        ),
    ]
