# Generated by Django 4.2.4 on 2023-09-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_script_manager", "0015_alter_scriptinstance_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptexecution",
            name="request_id",
            field=models.UUIDField(unique=True),
            preserve_default=False,
        ),
    ]
