# Generated by Django 4.2.4 on 2023-09-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_script_manager', '0016_scriptexecution_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptexecution',
            name='data',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
